// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef TI_MMWAVE_ROSPKG_MSGS__MSG__RADAR_MICRO_DOPPLER_FEATURE_CONTENTS_HPP_
#define TI_MMWAVE_ROSPKG_MSGS__MSG__RADAR_MICRO_DOPPLER_FEATURE_CONTENTS_HPP_

#include "ti_mmwave_rospkg_msgs/msg/detail/radar_micro_doppler_feature_contents__struct.hpp"
#include "ti_mmwave_rospkg_msgs/msg/detail/radar_micro_doppler_feature_contents__builder.hpp"
#include "ti_mmwave_rospkg_msgs/msg/detail/radar_micro_doppler_feature_contents__traits.hpp"
#include "ti_mmwave_rospkg_msgs/msg/detail/radar_micro_doppler_feature_contents__type_support.hpp"

#endif  // TI_MMWAVE_ROSPKG_MSGS__MSG__RADAR_MICRO_DOPPLER_FEATURE_CONTENTS_HPP_
